spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        validator:
          apply_to_ddl: true
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.type: info
    org.springframework.data.redis: debug
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    root: debug

jwt:
  secret: 4e1c9c6b3b9f82e1c1f8e1c8f8e1c1f8e1c9c6b3b9f82e1c1f8e1c8f8e1c1f8
  access_expiration: 900000
  refresh_expiration: 86400000