spring:
  datasource:
    url: jdbc:mysql://db:3306/codeit
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: codeit_user
    password: codeitteam3
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: codeit-team3.brhfwv.ng.0001.apn2.cache.amazonaws.com
      port: 6379
      password:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  h2:
    console:
      enabled: false # H2 사용 중지

logging:
  level:
    org.hibernate.type: info
    org.springframework.data.redis: debug
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.orm.jdbc.bind: trace
    root: info

jwt:
  secret: 4e1c9c6b3b9f82e1c1f8e1c8f8e1c1f8e1c9c6b3b9f82e1c1f8e1c8f8e1c1f8
  access_expiration: 900000
  refresh_expiration: 86400000

springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/**
