name: codeit-CICD

on:
  push:
    branches: [ dev ]

env:
  NAME: codeit
  REPO: bookco

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build
          build-root-directory: codeit

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{env.NAME}}/${{env.REPO}}:latest
#
#  deploy:
#    needs: build
#    name: Deploy
#    runs-on: [ self-hosted, label-development ]
#    steps:
#
#      - name: deploy run
#        run: |
#          sudo sh /home/ec2-user/run.sh